#!/bin/bash

func pubkey() {
    # cat ~/.ssh/id_rsa.pub | xclip
    # DISPLAY=:0 xclip -sel clip < ~/.ssh/id_rsa.pub
    # xclip -sel clip < ~/.ssh/id_rsa.pub
}

func work() {
    cd ~/Pictures/screenshots
    rm *.png
    pull_loop
    cd ~/Sites/

}

func pull_loop() {
    for dir in ~/Sites/*
    do
        dir=${dir%*/}
        cd ~/Sites/${dir##*/}
        git pull
        echo "${dir##*/}"
    done

}

func pubkey() {
    cd ~/.ssc
    cat id_rsa.pub
}

