#!/bin/bash

func pubkey() {
    # cat ~/.ssh/id_rsa.pub | xclip
    # DISPLAY=:0 xclip -sel clip < ~/.ssh/id_rsa.pub
    # xclip -sel clip < ~/.ssh/id_rsa.pub
}

func work() {
    cd ~/Pictures/screenshots
    rm *.png
    pull_loop
    cd ~/Sites/

}

func pull_loop() {
    for dir in ~/Sites/*
    do
        dir=${dir%*/}
        cd ~/Sites/${dir##*/}
        git pull
        echo "${dir##*/}"
    done

}

func pubkey() {
    cd ~/.ssc
    cat id_rsa.pub
}

func gstart() {
    echo '---'
    echo '\n'
    echo 'art optimize:clear'
    echo '\n'
    php artisan optimize:clear
    echo '---'
    echo '\n'
    echo 'composer dump-autoload'
    echo '\n'
    composer dump-autoload
    echo '---'
    echo '\n'
    echo 'npm install'
    echo '\n'
    npm install
    echo '---'
    echo '\n'
    echo 'composer install'
    echo '\n'
    composer install
    echo '---'
    echo '\n'
    echo 'artmf'
    echo '\n'
    php artisan migrate:fresh --seed
}
